[Autologin]
User=live
Session=cosmic.desktop

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Theme]
Current=silent-nyarch

[Users]
MaximumUid=60513
MinimumUid=1000
